### ISSUE TITLE
Only Show Zend_Debug's when you're only on your local

### ISSUE THREAD

**Issue by temyong** [omnithoper/zend-frameworks#1]
Debug dumps (Zend_Debug) are very useful when debugging. But for other dev's (specially when you are doing a release), this should not show on the web page.

Please create a local.ini specific flag to be able to specify if debug dumps are on or off so that you can control when those are displayed on the web site.

sample:
`
$config = new Zend_Config('PATH_TO_CONFIG_FILE');
if ($config->debug == 1) {
Zend_Debug::dump($studentsRecords);
}
`

**Comment by omnithoper** [comment]
close ni kuya z kagabe
