### ISSUE TITLE
Dont Let Student Enroll the Subject Already Enrolled

### ISSUE THREAD

**Issue by temyong** [omnithoper/zend-frameworks#3]
Currently, when trying to enroll a subject already enrolled, the ff error is encountered:
`Subject Already Exist
Notice: Undefined index: status in /home/temyong/workspace/git/projects/zend-enrollment/application/views/scripts/enrollment/index.phtml on line 40`

Please remove the selection on the "Enroll Subject" drop down choice when the subject is already listed on the enrolled subject lists.

**Comment by omnithoper** [comment]
nagawa ko din sa wakas
